apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 3  # 3개 모두가 동작하지 않을 것이다.
  template: # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release2
        resources:
          requests:
            memory: 3000Mi  # 테스트를 위해 3개를 실행시킬 수 없는 메모리 값으로 설정
