# 알림을 위한 테스트 파드로 이 파드는 시작되면 치명적인 오류로 갑자기 종료된다.
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bad-deployment
spec:
  selector:
    matchLabels:
      app: bad
  replicas: 2 
  template:
    metadata:
      labels:
        app: bad
    spec:
      containers:
      - name: bad
        image: ubuntu:18.04
        command: ["10 print('it is 1982')\ni20 goto 10"]
