# PagerDuty와 Dead Man's snitch를 사용할 때 사용하는 alertmanger.yaml
global:
  slack_api_url: 'YourSlackURL'
receivers:
- name: slackandPD
  pagerduty_configs:
  - service_key: 'YourPagerDutyAPIKey'
  slack_configs:
  - channel: '#channelname'
    icon_emoji: ':bell:'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.message }}\n"
- name: DMS
  webhook_configs:
  - send_resolved: false
    url: 'SnitchURL'
route:
  group_by:
  - alertname
  group_interval: 1m
  group_wait: 5s
  receiver: slackandPD
  repeat_interval: 10m
  routes:  # 아래 조건을 만족하면 위 규칙을 무시하고 여기에 정의된 대로 실행
  - match:
      alertname: Watchdog
    receiver: DMS
