apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # This defines which pods are going to be represented by this Services
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eq browsers)
  selector:
    app: webapp

  ports:
    - name: http
      port: 80

  type: LoadBalancer  # 직접 접속하지 않고 로드 밸런서를 통해 접근하도록 변경

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue

  ports:
    # queue에서 사용하는 관리자 콘솔(브라우저에 노출시킬 용도)
    - name: http
      port: 8161  # 컨테이너 내부에서 사용하는 포트

    # 컨테이너들이 메시지를 주고 받을 포트(외부에 노출 안 함)
    - name: endpoint
      port: 61616

  type: ClusterIP  # 큐는 이제 클러스터 내부에서만 확인하면 된다.

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:
  selector:
    app: position-tracker

  ports:
    # queue에서 사용하는 관리자 콘솔(브라우저에 노출시킬 용도)
    - name: http
      port: 8080  # 컨테이너 내부에서 사용하는 포트

  type: ClusterIP  # 클러스터 내부에만 노출

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway

spec:
  selector:
    app: api-gateway

  ports:
    # queue에서 사용하는 관리자 콘솔(브라우저에 노출시킬 용도)
    - name: http
      port: 8080  # 컨테이너 내부에서 사용하는 포트

  type: ClusterIP