# What do you want? (무엇을 원하는가?)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce  # 한 번에 다중 노드에 의해 마운트될 수 있는 볼륨을 원하는지에 대한 옵션
  resources:
    requests:
      storage: 7Gi  # db가 필요한 용량(물리적 저장소에 요구할 용량)

---

# How do we want it implemented? (어떻게 실행할 것인가?)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: ebs.csi.aws.com
parameters:
  type: gp2